<?php

/**
 * @file
 * Like_dislike module file.
 */

/**
 * Implements hook_theme().
 */
function like_dislike_theme() {
  return [
    'like_dislike' => [
      'variables' => [
        'likes' => NULL,
        'dislikes' => NULL,
        'disable' => NULL,
        'like_url' => NULL,
        'dislike_url' => NULL,
        'entity_id' => NULL,
        'likes_label' => NULL,
        'dislikes_label' => NULL,
      ],
    ],
  ];
}
